# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'score' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for score
    pod 'Alamofire', '~> 3.0'
    pod 'SnapKit', '~> 0.0'
    pod 'YapDatabaseExtensions'
    pod 'Cosmos', '~> 1.2'
end
